<a href="https://colab.research.google.com/github/lucimidori92/Estudos_Engenharia_Dados/blob/main/Numpy_Lista.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy  X Listas


In [4]:
# ! pip install numpy
import numpy as np

In [5]:
s_lista = [[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]]
s_lista

[[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]]

In [6]:
type(s_lista)

list

In [7]:
# criação do objeto matriz
s_array = np.array(s_lista)
type(s_array)

numpy.ndarray

In [8]:
s_array[0][3]

8

In [16]:
# 2 dimensões [externo - semestre, interno - prova]

s_array[0, -3]

6

In [21]:
type([1, 'a'][0])
type([1, 'a'][1])

str

In [22]:
np.array([1, 'a'])

array(['1', 'a'], dtype='<U21')

In [26]:
type(np.array([1, 'a'])[0])
type(np.array([1, 'a'])[1])

numpy.str_

In [23]:
s_array.dtype

dtype('int64')

In [27]:
# ndim mostra quantas dimensões há dentro do objeto
s_array.ndim

2

In [44]:
# não é possível somar um inteiro com lista: s_lista + 1
s_array * 2

array([[20, 12,  8, 16],
       [18,  4, 10, 10],
       [ 2,  4, 20, 20]])

In [41]:
s_lista = [[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]]
for lista in s_lista:
  for nota in lista:
    nota += 1
    print(nota)

11
7
5
9
10
3
6
6
2
3
11
11


In [45]:
s_array % 2

array([[0, 0, 0, 0],
       [1, 0, 1, 1],
       [1, 0, 0, 0]])

In [53]:
result = []
for index in range(len(s_lista)):
  result.append([])
  for item in s_lista[index]:
    update = item % 2
    result[index].append(update)
print(result)

[[0, 0, 0, 0], [1, 0, 1, 1], [1, 0, 0, 0]]


In [10]:
s_lista

[[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]]

In [13]:
s_array % 2 == 0

array([[ True,  True,  True,  True],
       [False,  True, False, False],
       [False,  True,  True,  True]])

In [14]:
# máscara - true or false, para filtragem
is_par = s_array % 2 == 0
s_array[is_par]

array([10,  6,  4,  8,  2,  2, 10, 10])

# Operações booleanas
- not -> ~
- and -> &
- or -> |
- xor -> ^

In [16]:

s_array[~ is_par]


array([9, 5, 5, 1])

In [24]:
is_multi_5 = s_array % 5 == 0
filter = is_multi_5 & is_par
s_array[filter]

array([10, 10, 10])

In [29]:
a_lista = [s_lista, s_lista]

a_lista

[[[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]],
 [[10, 6, 4, 8], [9, 2, 5, 5], [1, 2, 10, 10]]]

In [31]:
a_vetor = np.array(a_lista)
a_vetor

array([[[10,  6,  4,  8],
        [ 9,  2,  5,  5],
        [ 1,  2, 10, 10]],

       [[10,  6,  4,  8],
        [ 9,  2,  5,  5],
        [ 1,  2, 10, 10]]])

In [33]:
# [ano, semestre, prova-nota]

a_vetor[1, 0, -1]

8

In [37]:
a_vetor[1, :, :] = a_vetor[1, :, :] + 1
a_vetor

array([[[10,  6,  4,  8],
        [ 9,  2,  5,  5],
        [ 1,  2, 10, 10]],

       [[12,  8,  6, 10],
        [11,  4,  7,  7],
        [ 3,  4, 12, 12]]])

In [38]:
# puxa todos os anos, todos os semestres, a última prova
a_vetor[:, :, -1]

array([[ 8,  5, 10],
       [10,  7, 12]])

In [39]:
a_vetor[:, :, -2]

array([[ 4,  5, 10],
       [ 6,  7, 12]])

In [40]:
a_vetor[:, :, [0, -1]]

array([[[10,  8],
        [ 9,  5],
        [ 1, 10]],

       [[12, 10],
        [11,  7],
        [ 3, 12]]])

In [41]:
ano = [0, 1, 1]
semestre = [0, 0, 1]
prova = [0, 1, 2]

a_vetor[ano, semestre, prova]


array([10,  8,  7])

In [42]:
a_vetor.shape

(2, 3, 4)

# Criação


In [49]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar or array_like
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         ``np.array(fill_value).dtype``.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible wit

In [48]:
np.full([2, 3, 4], 2)


array([[[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]],

       [[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]]])

In [51]:
np.arange(2, 21, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [58]:
# import random
# random.randint
# randint - começa pelo zero, vai até 10 (11-1), e o shape do meu array (2, 3, 4)
np.random.randint(0, 11, (2, 3, 4))

array([[[ 1,  8,  0,  8],
        [ 4, 10,  1,  4],
        [ 3,  0,  7,  5]],

       [[ 9,  4,  1,  8],
        [ 1,  1,  3,  2],
        [ 7,  8,  5,  6]]])

In [63]:
np.round(np.random.uniform(0, 11, (2, 3, 4)), 2)

array([[[ 1.97,  6.41,  3.93,  9.98],
        [ 0.55,  6.87,  1.18,  6.36],
        [ 2.57, 10.41,  1.17,  7.32]],

       [[ 0.52,  7.44,  2.77,  3.34],
        [ 6.9 ,  7.72,  6.92,  7.38],
        [ 9.59,  2.63,  6.6 ,  4.24]]])

In [64]:
np.random.choice(['aprovado', 'reprovado'], (2, 3, 4))

array([[['reprovado', 'aprovado', 'aprovado', 'aprovado'],
        ['reprovado', 'aprovado', 'aprovado', 'reprovado'],
        ['reprovado', 'reprovado', 'aprovado', 'reprovado']],

       [['aprovado', 'aprovado', 'aprovado', 'reprovado'],
        ['aprovado', 'aprovado', 'reprovado', 'reprovado'],
        ['reprovado', 'reprovado', 'aprovado', 'aprovado']]], dtype='<U9')